excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

disabled_rules:
    - unused_closure_parameter

line_length: 144

cyclomatic_complexity:
    warning: 10
    error: 30

function_parameter_count:
    warning: 10
    error: 20
