excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Endangered\ Waves/image-picker/* # Used to be a CocoaPod but had to be modified so was brought in

disabled_rules:
    - unused_closure_parameter

line_length: 144

file_length: 600

function_body_length: 60

cyclomatic_complexity:
    warning: 10
    error: 30

function_parameter_count:
    warning: 10
    error: 20
